version: '3.3'
services:
  news:
    image: news
    container_name: news
    ports:
    - "5000:5000"
    command: 'npm run test && npm run lint'
    environment:
    - NODE_ENV=ci
    depends_on:
    - database
  database:
    container_name: database
    hostname: database
    image: database
    ports:
    - "27017:27017"